packages:
  - "packages/eslint-config/*"
  - "packages/prettier-config/*"
  - "packages/vscode-config/*"
  - "packages/stylelint-config/*"
  - "packages/templates/*"
  - "packages/tpl/*"
  - "packages/download/*"
